---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by she.
--- DateTime: 2025-10-19 14:09
---
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0;